### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Trilarion** [textbrowser/maxit#1]
It seems that no license information is included in this repository or I could not find it. Is it possible to specify the code and artwork licenses of Maxit?

**Comment by textbrowser** [comment]
Sure.

**Comment by textbrowser** [comment]
Added a LICENSE file for the source.

**Comment by Trilarion** [comment]
Thanks.

**Comment by textbrowser** [comment]
I don't know where I copied the images from.

**Comment by Trilarion** [comment]
If I have some time, I can help finding out.

**Comment by textbrowser** [comment]
New Images/COPYRIGHT file.

"Maxit does not own the copyrights of the images."

Would you prefer other text?

**Comment by Trilarion** [comment]
The text is good. The images are most likely free. Just need to find some sources.

**Comment by textbrowser** [comment]
Did you locate the sources?

**Comment by textbrowser** [comment]
Silent user. Closing.
